global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.120:9000' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'API Gateway'

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.120:18080'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Product Service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.120:18081'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Order Service'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.120:18082' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Inventory Service'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.120:18083' ] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Notification Service'

