---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://192.168.1.121:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://192.168.1.121:9411"
  PRODUCT_SERVICE_URL: "http://product-service.default.svc.cluster.local:8080"
  ORDER_SERVICE_URL: "http://order-service.default.svc.cluster.local:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service.default.svc.cluster.local:8082"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "192.168.1.121:29092"